/**
 * Do not edit this file manually!
 * This file is automatically generated by generate_auto_rules.py
 */


#include "ebpf_ids_common.h"


static inline uint32_t
__auto_rules_tcp(struct bpfhv_pkt* pkt) {
	struct iphdr* ip_header = get_ip_header(pkt);
	struct tcphdr* tcp_header = get_tcp_header(pkt);
	if(ip_header->saddr == IPADDR_BE(10,0,0,10) && be16_to_cpu(tcp_header->dest) == 9898) {
		return IDS_LEVEL(6);
	}
	return IDS_PASS;
}


static inline uint32_t
__auto_rules_udp(struct bpfhv_pkt* pkt) {
	struct iphdr* ip_header = get_ip_header(pkt);
	struct udphdr* udp_header = get_udp_header(pkt);
	if(be16_to_cpu(udp_header->dest) == 9898 && ip_header->saddr == IPADDR_BE(10,0,0,10)) {
		return IDS_LEVEL(6);
	}
	return IDS_PASS;
}
